import type { Metadata } from "next";
import { oneShinhan } from "@/styles/fonts";
import "./globals.css";
import { Header } from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oneShinhan.variable} antialiased bg-[#F1F3F8]`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
